apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: url-shortener-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: url-shortener-dev
spec:
  project: default
  source:
    repoURL: https://github.com/SVendittelli/vendittelli.co.uk-k8s.git
    targetRevision: HEAD
    path: url-shortener/overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: url-shortener-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: url-shortener-prod
spec:
  project: default
  source:
    repoURL: https://github.com/SVendittelli/vendittelli.co.uk-k8s.git
    targetRevision: HEAD
    path: url-shortener/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
