apiVersion: apps/v1
kind: Deployment
metadata:
  name: nom-de-plume
spec:
  selector:
    matchLabels:
      app: nom-de-plume
  template:
    metadata:
      labels:
        app: nom-de-plume
    spec:
      containers:
        - name: nom-de-plume
          image: vendittelli/nom-de-plume:1.5.10@sha256:1ba40b99dc775f3dcaa79bc87345754a3a5d917b66493e50ffe79317852e6066
          envFrom:
            - secretRef:
                name: nom-de-plume
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1"
  revisionHistoryLimit: 0
