apiVersion: apps/v1
kind: Deployment
metadata:
  name: nom-de-plume
spec:
  selector:
    matchLabels:
      app: nom-de-plume
  template:
    metadata:
      labels:
        app: nom-de-plume
    spec:
      containers:
        - name: nom-de-plume
          image: vendittelli/nom-de-plume:1.3.6@sha256:8095ebcf9753107b6d98c7dda4dce02e7598253fd7114e729ba44db4c2bae54e
          envFrom:
            - secretRef:
                name: nom-de-plume
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1"
  revisionHistoryLimit: 0
